INSERT INTO INVENTORY(BRAND_NAME, COUNT, CATEGORY_ID)
VALUES ('RUNWELL', 957, 1),
('CANFIELD', 846, 1),
('BIRDY', 732, 1),
('RUNWELL BACKPACK', 52, 2),
('JOURNAL COVER', 216, 2),
('BIFOLD WALLET', 358, 2);

INSERT INTO CATEGORY(BRAND_NAME)
VALUES ('WATCHES'),
('LEATHER');
